import os


if os.getenv('ENVIRONMENT') == 'custom':
    tick = ""
    no = ""
    Warning = ""
    Settings = ""
    folder = ""
    pen = ""
    tagsemoji = None
    infractions = ""
    promotions = ""
    dropdown = ""
    greencheck = ""
    redx = ""
    cpending = ""
    bin = ""
    add = ""
    replytop = ""
    replymiddle = ""
    replybottom = ""
    smallarrow = ""
    arrow = ""
    star = ""
    crisis = ""
    loa = ""
    redxbox = ""    
else:
    tick = ""
    no = ""
    Warning = ""
    Settings = ""
    folder = ""
    pen = ""
    tagsemoji = None
    infractions = " "
    promotions = ""
    dropdown = ""
    greencheck = ""
    redx = ""
    cpending = ""
    bin = ""
    add = ""
    replytop = ""
    replymiddle = " "
    replybottom = ""
    smallarrow = ""
    arrow = ""
    star = ""
    crisis = ""
    loa = ""
    redxbox = ""
